from queue import Queue

browser = None
context = None
all_info = {}

productQu = Queue()
unknownQu = Queue()
productInt = 0

task_list_QuA = Queue()
task_list_QuB = Queue()
taskcountInt = 0

suc_login_Qu = Queue()
fail_login_Qu = Queue()
check_login_Qu = Queue()

all_result = []

class cfg:
    debug = False
    err_log_file = '0-errlog.txt'
    unknown_device_file = '1-unknown_devices.txt'
    suc_login_file = '2-success.txt'
    fail_login_file = '3-fail.txt'
    watch_file = '4-check.txt'

    pass_dict_dir = './pass_dict'
    help_info = '''
    user_info：是包含username 字段名和字典目录的元组，pass_info类似
    keywords：是识别产品的关键词列表，与关系
    CAPTCHA: 长度一般为2，位置0位填充，位置1为截图
    suc:成功判断，根据logic计算整体真假
    fail:失败判断，根据logic计算整体真假
    '''
    pass_dict = {
        # 网络设备
        'CentOS':{
            'keywords': ['CentOS Linux', 'badge'],
            'user_info': ['#login-user-input', 'pass_dict/0-admin1.txt'],
            'pass_info': ['//*[@id="login-password-input"]', 'pass_dict/1-top1000.txt'],
            'button': ['button:has-text(\"登录\")'],
            'CAPTCHA': [],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},

        '奇安信网神全流量威胁发现系统':{
            'keywords': ['奇安信网神', '全流量威胁发现系统'],
            'user_info': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[1]', 'pass_dict/0-admin.txt'],
            'pass_info': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[2]', 'pass_dict/1-qaxty.txt'],
            'button': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[2]/input'],
            'CAPTCHA': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[3]', '/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/div/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '奇安信网神新一代安全感知系统':{
            'keywords': ['奇安信网神新一代安全感知系统', '新一代安全感知系统'],
            'user_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[1]/input', 'pass_dict/0-admin.txt'],
            'pass_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[2]/input', 'pass_dict/1-qaxty.txt'],
            'button': ['//*[@id="app-main-component"]/div/div[4]/div[2]/button'],
            'CAPTCHA': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/input', '//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '奇安信网神流量传感器':{
            'keywords': ['奇安信网神', '流量传感器'],
            'user_info': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[1]', 'pass_dict/0-admin.txt'],
            'pass_info': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[2]', 'pass_dict/1-qaxty.txt'],
            'button': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[2]/input'],
            'CAPTCHA': ['/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/input[3]', '/html/body/div/div[2]/div/div/div[1]/div/div/div[2]/form/div[1]/div/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '奇安信天眼分析平台':{
            'keywords': ['奇安信天眼分析平台', 'update.skyeye.qianxin.com'],
            'user_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[1]/input', 'pass_dict/0-admin.txt'],
            'pass_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[2]/input', 'pass_dict/1-qaxty.txt'],
            'button': ['//*[@id="app-main-component"]/div/div[4]/div[2]/button'],
            'CAPTCHA': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/input', '//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '奇安信网神分析平台':{
            'keywords': ['奇安信网神分析平台', 'update.skyeye.qianxin.com'],
            'user_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[1]/input', 'pass_dict/0-admin.txt'],
            'pass_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[2]/input', 'pass_dict/1-qaxty.txt'],
            'button': ['//*[@id="app-main-component"]/div/div[4]/div[2]/button'],
            'CAPTCHA': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/input', '//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '奇安信威胁分析系统':{
            'keywords': ['奇安信威胁分析系统', 'update.skyeye.qianxin.com'],
            'user_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[1]/input', 'pass_dict/0-admin.txt'],
            'pass_info': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[2]/input', 'pass_dict/1-qaxty.txt'],
            'button': ['//*[@id="app-main-component"]/div/div[4]/div[2]/button'],
            'CAPTCHA': ['//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/input', '//*[@id="app-main-component"]/div/div[4]/div[2]/div[3]/img'],
            'suc': [],
            'fail': [],
        	'logic': ['or'],
		},
        '宇视NVR地址':{
            'keywords': ['pluginVersionTip', 'szUserPasswdSrc'],
            'user_info': ['input[name=\"szUserName\"]', 'pass_dict/0-yssxt.txt'],
            'pass_info': ['input[type=\"password\"]', 'pass_dict/1-yssxt.txt'],
            'button': ['//*[@id="login"]/span[2]'],
            'CAPTCHA': [],
            'suc': ['stUserLoginIP'],
            'fail': ['name=\"szUserName\"'],
        	'logic': ['or'],
		},
        '深信服产品':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sangfor.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sangfor.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网御WAF集中控制中心(V3.0R5.0)':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-leadsec.waf.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联想网御':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-lxwy.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网御漏洞扫描系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-leadsec.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天阗入侵检测与管理系统 V7.0':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-venus60.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联想网御防火墙PowerV':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-lxwy.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联想网御入侵检测系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-lenovo.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-default.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联想网御防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-leadsec@7766.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网络卫士入侵检测系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-talent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网御入侵检测系统V3.2.72.0':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-leadsec32.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联想网御入侵检测系统IDS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-lxwyids.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '科来网络回溯分析系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-csadmin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-colasoft.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中控考勤机web3.0':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C iMC':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C SecPath系列':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C S5120-SI':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-test.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C智能管理中心':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C ER3':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-adminer3100.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C SecPath ACG1000':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-h3c.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-adminer.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'H3C web网管用户登录':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-h3capadmin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360天擎':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网神防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-firewall.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天融信防火墙NGFW4000':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-talent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天融信防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-talent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '黑盾防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-hdfw.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-hdfw.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华为防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-hdfw.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-hdfw.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '方正防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '飞塔防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-lenovo.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-empty.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'Juniper_SSG__5防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-netscreen.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-netscreen.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中新金盾硬件防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'kill防火墙(冠群金辰)':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sys123.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天清汉马USG防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-useradmin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-venus.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '阿姆瑞特防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-manager.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '山石网科网络安全审计系统':{
            'keywords': ['山石网科网络安全审计系统', '/webui/css/'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-hillstone.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-hillstone.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'TopAudit日志审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-talent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'LogBase日志管理综合审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-safetybase.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网神SecFox运维安全管理与审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-secfox.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网神防火墙GE1口':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天融信数据库审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-telent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '堡垒机V2.0':{
            'keywords': ['堡垒机V2.0', '/static/img/logo.png', 'col-md-12 hehe_copyright'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密码\"]', 'pass_dict/1-admin.txt'],
            'button': ['text=登录'],
            'CAPTCHA': [],
            'suc': ['主页'],
            'fail': ['用户名或密码不正确'],
        	'logic': ['or'],
		},
        'Hillstone安全审计平台':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-hillstone.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-hillstone.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网康日志中心':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-ns25000.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-ns25000.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '网络安全审计系统（中科新业）':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天玥网络安全审计系统':{
            'keywords': ['天玥网络安全审计系统', '/webui/css/'],
            'user_info': ['input[name=\"usr\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"pwd\"]', 'pass_dict/1-cyberaudit.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['input[name=\"validate\"]'],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御WEB应用防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御安全网关':{
            'keywords': ['明御安全网关', 'webui/css/reset.css', '/webui/js'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-sapling.txt'],
            'button': ['button:has-text(\"登录\")'],
            'CAPTCHA': ["input[name=\"vldcode\"]","#myvld"],
            'suc': ['首页','授权提醒'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御政务专网互联防火墙':{
            'keywords': ['政务专网互联防火墙', 'webui/css/reset.css', '/webui/js', '杭州安恒信息'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-sapling.txt'],
            'button': ['button:has-text(\"登录\")'],
            'CAPTCHA': [],
            'suc': ['首页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御攻防实验室平台':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御运维审计与册风险控制系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-myywsj.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-myywsj.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御网站卫士':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sysmanager.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sysmanager.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '明御APT':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-Dbapp@2014.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '亿邮邮件网关':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-eyouuser.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-eyouuser.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'Websense邮件安全网关':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '梭子鱼邮件存储网关':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天清web应用安全网关':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-venus70.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '辰泰和信息安全运营中心':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sysadmin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-venus1.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '启明星辰':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-qmxc.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'juniper':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-netscreen.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-netscreen.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'Cisco':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-cisco.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '齐治堡垒机':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-shterm.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-shterm.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        # 路由器
        '维盟路由器':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '铱讯 Yxlink WAF':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sysadmin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-default.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'IBM IMM 集成管理模块':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-IBMIMM.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-IBMIMM.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大华监控设备':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '锐捷NBR系列':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-manager.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-manager.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华夏创新AppEx、Lotware、LotWan、LotFlow、LotAccess、LotBalance、LotMobile以及华创路由器':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '深信服VPN':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '深信服ipsec-VPN (SSL 5.5)':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天融信VPN':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-test.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华为VPN':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-mduadmin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '全向QL1680/1688':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-qxql.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-qxql.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '全向QL1880':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'TP-LINKTD-8800':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '合勤zyxel642':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-telnet.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'EcomED-802EG':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '神州数码6010RA':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-ADSL.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-ADSL.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华为SmartAXMT800':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '伊泰克':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-supervisor.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华硕路由器':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-ADSL.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-ADSL.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '同维DSL699E':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大亚DB102':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-dare.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'WST的RT1080':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'WST的ART18C':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-conexant.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '实达ADSL2110-EH':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-starnetadsl.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '泛德用户':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-conexant.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '东信Ea700':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-empty.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'broadmax hsa300a':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-broadmax.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-broadmax.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '长虹ch-500E':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '重庆普天CPADSL03':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '台湾突破EA110RS232:38400':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-SL.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-SL.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'etek-td的ADSL_T07L006.0':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-supervisor.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'GVC的DSL-802E/R3A':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-epicrouter.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '科迈易通km300A-1':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-empty.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '科迈易通km300A-G':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '易通km300A-A':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123456.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'sunrise的SR-DSL-AE':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-0000.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'sunrise的DSL-802E_R3A':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-epicrouter.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'UTStar的ut-300':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-utstar.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '湖北邮通':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-epicrouter.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '亨威NSM500网速通':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-root.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '艾玛701g':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '艾玛701H':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-epicrouter.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '实达2110EHROUTER':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-user.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '普天':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-root.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-dare.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'zyxel':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-anonymous.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'e-tek':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '北电':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-anonymous.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大恒':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大唐':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '斯威特':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-user.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-user.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中兴':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-adsl.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-adsl.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        # 中间件
        'tomcat':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-tomcat.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-tomcat.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'weblogic':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-weblogic.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-weblogic.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'Jboss':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-jboss.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-jboss.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'jonas':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-jonas.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-jonas.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        # 战略客户产品
        'SG-8000深度安全网关':{
            'keywords': ['SG-8000深度安全网关', 'webui/images'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-firewall.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['首页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '应急拦截网关':{
            'keywords': ['应急拦截网关','/webui/js/jquerylib/'],
            'user_info': ['input[name=\"USER\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"PASSWORD\"]', 'pass_dict/1-sapling.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'AG6000 上网行为管理':{
            'keywords': ['AG6000 上网行为管理', '登录web管理系统', '/webui/js/'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-sapling.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '统一上网行为管理':{
            'keywords': ['统一上网行为管理', '/webui/js/'],
            'user_info': ['input[name=\"USER\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"PASSWORD\"]', 'pass_dict/1-sapling.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安博通入侵防御系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sapling.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中性下一代防火墙':{
            'keywords': ['/webui/js/','input name="USER"','5LiL5LiA5Luj6Ziy54Gr5aKZ'],
            'user_info': ['input[name=\"USER\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"PASSWORD\"]', 'pass_dict/1-sapling.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '策略可视化平台':{
            'keywords': ['策略可视化平台','/sso/assets/js/bootstrap/','/assets/images/'],
            'user_info': ['[placeholder=\"请输入用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密码\"]', 'pass_dict/1-sapling.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"输入验证码\"]'],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '启明星辰上网行为管理':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-venustech.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '启明星辰leadsec':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-leadsec.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华为上网行为管理':{
            'keywords': ['/webui/images/basic/icons/favicon', 'huawei_title','华为技术有限公司'],
            'user_info': ['input[name=\"username\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"password\"]', 'pass_dict/1-admin.txt'],
            'button': "text=登 录",
            'CAPTCHA': ['input[name=\"vldcode\"]'],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '迪普 FW1000-GA-E':{
            'keywords': ['杭州迪普科技股份有限公司', '/func/web_main/display/frame/main'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密码\"]', 'pass_dict/1-admin_default.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['基本'],
            'fail': ['登录失败'],
        	'logic': ['or'],
		},
        '华三上网行为管理':{
            'keywords': ['Web User Login', '/webui/images/basic/', '新华三'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-admin.txt'],
            'button': ['text=登 录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '卓智防火墙JW-iNGFW 9000':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '飞鱼星防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '任子行网络安全审计系统':{
            'keywords': ['任子行网络安全审计系统', '/webui/js/', '任子行网络技术股份有限公司'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-rzxuac.txt'],
            'button': ['a:has-text(\"登录\")'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '任子行防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中兴皖通':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-zxwt.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中新网安上网行为管理':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火虹旭上网行为管理':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '国槐FW':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '广州蓝盾fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-Bluedon.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '蓝盾信息安全管理审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-Bluedon.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '蓝盾流量控制管理系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-Bluedon.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '纳斯威尔uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '爱思uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-nfas68697282.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '圣博润fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安美微客uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '迈普UAC':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '迈普防火墙（千兆）':{
            'keywords': ['迈普', '/webui/images/maipu/'],
            'user_info': ['[placeholder=\"请输入用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"请输入密码\"]', 'pass_dict/1-maipu.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '迈普IPS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '格勤uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '成都康乔ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-KQAdmin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-KQAdmin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中科网威fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-system.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-netpower.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中科网威uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'D-Link uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '博达uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '博达fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '博达海康fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '金电网安':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin2003.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '技腾fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '兴唐科技fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '神州云科fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '逸云fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '绿盟安全审计系统':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-weboper.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-weboper.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '绿盟fw':{
            'keywords': ['NSFOCUS', '绿盟科技', '/webui/images/'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-sapling.txt'],
            'button': "text=登录",
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '绿盟uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '绿盟自研防火墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-weboper.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-weboper.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '绿盟无线非经':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '敦崇uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-dunchong.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安点科技':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '龙腾佳讯':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-ltjx.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '胜云光电':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '兴唐密安':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中广核（威努特）':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '威努特工业互联防火墙':{
            'keywords': ['工业互联防火墙', '/webui/images/basic/login'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-admin.txt'],
            'button': ['text=登录'],
            'CAPTCHA': [],
            'suc': ['主页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '广州光迅fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '广州光迅uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '广州光迅ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '城市热点fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-ishare.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-123.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-1234.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '宇视视频安全网关':{
            'keywords': ['视频安全网关', '/webui/js/'],
            'user_info': ['input[name=\"usr\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['input[name=\"pwd\"]', 'pass_dict/1-sapling.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['首页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安博通容器安全入侵检测平台':{
            'keywords': ['安博通容器安全入侵检测平台', '/Public/assets/js/'],
            'user_info': ['[placeholder=\"请输入账号\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"请输入密码\"]', 'pass_dict/1-sapling.txt'],
            'button': ['text=登录'],
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['首页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中科大洋':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '国路安':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-gla.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'Japanese fw GresAVAIL-FW':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '瑞斯康达fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '瑞斯康达uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '万网博通fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '神帆 CHS-FW8000':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '睿峰网云fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-administrator.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '电子科技uac CETC54':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '数梦工厂uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '融智通uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '上海弘积uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '上海弘积fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '天津电安':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '捷成fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-administrator.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-password.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '富桥uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华依fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华博uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '科东fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '方正fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '方正uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '紫光uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '紫光fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '紫光ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '棕榈fw ZXSEC US':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '智驰uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '智驰fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '蓝盾（北京）uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '蓝盾（北京）fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '鼎普fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'O2亿赛通fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '联华中安IPS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '华电天任UAC':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '锐捷fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '思普崚uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '思普崚fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '思普崚IPS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安恒海康':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin12345.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '智网安云uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '智网安云fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '优炫uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '优炫fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '优炫IPS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '706所fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '利谱信息fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '星天卫（任子行）uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '清风合创ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '慧林fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火（新）uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-fiberhome.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-fiberhome.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火（新）fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-fiberhome.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-fiberhome.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '烽火（新）ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-fiberhome.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-fiberhome.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '上海金途uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '上海金途fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-firewall.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '威努特IPS':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安盟fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '安盟ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-superman.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-talent.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '北信源fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-bxy.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '北信源ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-bxy.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '亚信安全下一代防火墙':{
            'keywords': ['/webui/images/', '亚信安全下一代防火墙', '/php/common/checknum_creat.php'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-yx.txt'],
            'button': "text=登 录",
            'CAPTCHA': ['[placeholder=\"验证码\"]'],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '亚信ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-yx.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '立思辰 二代墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '立思辰ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '立思辰ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '立思辰 工控墙':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中孚fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sm.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sm.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '中孚ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-sm.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-sm.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大华uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '大华fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360 fw':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360 ids':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360 ips':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360 uac':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': ['数据中心'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        '360工业入侵检测系统':{
            'keywords': ['360工业入侵检测系统', 'webui/images'],
            'user_info': ['[placeholder=\"用户名\"]', 'pass_dict/0-admin.txt'],
            'pass_info': ['[placeholder=\"密　码\"]', 'pass_dict/1-sapling.txt'],
            'button': ["text=登录"],
            'CAPTCHA': [],
            'suc': ['首页'],
            'fail': ['用户名'],
        	'logic': ['or'],
		},
        'common_no_CAPTCHA':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': [''],
            'fail': [''],
        	'logic': ['or'],
        },
        'common_CAPTCHA':{
            'keywords': [],
            'user_info': ['USERNAME', 'pass_dict/0-admin.txt'],
            'pass_info': ['PASSWORD', 'pass_dict/1-admin.txt'],
            'button': ['a'],
            'CAPTCHA': [],
            'suc': [''],
            'fail': [''],
        	'logic': ['or'],
		},
        
    }


